swagger: "2.0"

info:
  title: "My API documentation"
  version: "1.0"
  description: "This is a simple minimal REST API microservice.\nThe base-path of the API is `/v1.0`"
  contact:
    name: Nelson Wan
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

basePath: /steamdiscount

schemes:
 - http
securityDefinitions:
  basicAuth:
    type: basic
    x-basicInfoFunc: api.accounts.basic_auth


paths:
  /games:
      get:
        tags:
        - public
        operationId: api.accounts.read_all_games
        responses:
          '200':
            description: 'Fetch all users from the database'
            schema:
                $ref: '#/definitions/User'
  /games/createUser:
    post:
      tags:
      - admins
      operationId: api.accounts.create_user
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: steamUser
        description: Inventory user to add
        schema:
          $ref: '#/definitions/User'
          type: object
      responses:
        201:
          description: Successfully added user to the DB
        400:
          description: invalid input, object invalid
        409:
          description: an existing item already exists

  /games/updateUser:
    put:
      tags:
      - admins
      operationId: api.accounts.update_user
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: updateUser
        description: Inventory item to add
        schema:
          $ref: '#/definitions/User'
      responses:
        201:
          description: Successfully added user to the DB
        400:
          description: invalid input, object invalid
        408:
          description: error, item not modified
        409:
          description: an existing item already exists
    
  /games/deleteUser/{deleteUser}:
    delete:
        tags:
        - admins
        parameters:
          - in: path
            name: deleteUser
            type: string
            required: true
            description: Numeric ID of the user to delete.
        operationId: api.accounts.delete_user
        responses:
          200:
            description: Successfully deleted user
          400:
            description: invalid input, object invalid
          409:
            description: conflict error
          401:
            description: Not correctly authorized

  /games/{gameTitle}:
      get:
        tags:
        - public
        operationId: api.accounts.read_game_by_title
        parameters:
          - in: path
            name: gameTitle
            type: string
            required: true
            description: Numeric ID of the user to get.
        responses:
          '200':
            description: 'Fetch a user from the database'
            schema:
                $ref: '#/definitions/User'

  # /games/steamspecials:
  #   get:
  #     tags:
  #     - public
  #     operationId: api.accounts.get_steam_specials
  #     responses:
  #       '200':
  #         description: 'Fetch discounted games from Steam'
  #         schema:
  #           type: object
  #           properties:
  #             games:
  #               type: array
  #               items:
  #                 type: object
  #                 properties:
  #                   title: { type: string }
  #                   discount: { type: string }
  #                   price: { type: string }
  #                   link: { type: string }
      

# tags are used for organizing operations
tags:
- name: public
  description: Operations available to regular developers
- name: admins
  description: Secured Admin-only calls

definitions:
  User:
    type: object
    properties:
      id:  { type: string }
      username: { type: string }
      password: { type: string }